// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI-powered tool recommendation wizard for new users.
 *
 * - recommendTool - A function that recommends the best AI tool based on a task description.
 * - RecommendToolInput - The input type for the recommendTool function.
 * - RecommendToolOutput - The return type for the recommendTool function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendToolInputSchema = z.object({
  taskDescription: z
    .string()
    .describe('A brief description of the task the user wants to accomplish.'),
});
export type RecommendToolInput = z.infer<typeof RecommendToolInputSchema>;

const RecommendToolOutputSchema = z.object({
  toolName: z.string().describe('The name of the recommended AI tool.'),
  toolDescription: z.string().describe('A brief description of the recommended AI tool.'),
  justification: z.string().describe('The justification for recommending this tool for the given task.'),
});
export type RecommendToolOutput = z.infer<typeof RecommendToolOutputSchema>;

export async function recommendTool(input: RecommendToolInput): Promise<RecommendToolOutput> {
  return recommendToolFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendToolPrompt',
  input: {schema: RecommendToolInputSchema},
  output: {schema: RecommendToolOutputSchema},
  prompt: `You are an AI assistant designed to recommend the best AI tool for a user based on their task description.

  Analyze the task description provided by the user and recommend the most suitable AI tool from the following list:

  - Article Summarizer: Summarizes long articles into concise summaries.
  - Sentiment Analyzer: Analyzes the sentiment of a given text.
  - Grammar Corrector: Corrects grammatical errors in a given text.
  - Image Generator: Generates images based on text prompts.

  Provide a brief description of the recommended tool and a justification for why it is the best choice for the user's task.

  Task Description: {{{taskDescription}}}
  `,
});

const recommendToolFlow = ai.defineFlow(
  {
    name: 'recommendToolFlow',
    inputSchema: RecommendToolInputSchema,
    outputSchema: RecommendToolOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
